# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9955fd42344c04688efb2a2d868c9142d08da1d2861a68abacbb6cbb4e094e5017c3190dee74b38944bf68c24e35848276f52eb7202c578f1567a3111c7d3b

test:
  secret_key_base: ec23655550d1df14e974d439e593ec9137c903a5b0d0c6833e65c88170de455b89a480d4b309d70615487ac5e1da53e1048da48ff72cba42e0fc94b0f4b91ca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
